server {
  listen 80;
  server_name 0.0.0.0;
  root /usr/share/nginx/html;
  index index.html index.htm;

  # Use relative redirects to preserve HTTPS from reverse proxy
  absolute_redirect off;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
