version: '2.19.1'

services:
  frontend:
    hostname: localhost
    build: frontend
    ports:
      - "8181:80"

  backend:
    build: backend
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /data/db
