export type User = {
  username?: string,
  firstname: String,
  lastname: String,
  email: String,
  respect: Number,
  level: String,
  questions: [],
  comments: [],
  subcomments: [],
  circles: [],
  followedQuestions: [],
  followedCircles: [],
  numOfCircles?: number,
  numOfQuestions?: number,
}
